version: "2"
services:
  node:
    container_name: site.epesados.prod
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    networks:
      - epesados
    ports:
      - "80:80"
    volumes:
      - ./static/:/usr/share/nginx/html
networks:
  epesados:
    external: true
